---
Name: silverstripe-4-5-compatibility
Only:
  classexists: 'SilverStripe\Control\Email\SwiftMailer'
---
SilverStripe\ORM\DataList:
  extensions:
    - Sunnysideup\Silverstripe4To5Compatibility\Extensions\DataListExtension
